### PR TITLE
Resolves error when following personal account instructions.

### PR DESCRIPTION
**Pull request by zakiya**
Fixing: 
pantheon-error

### CODE REVIEW

**Review by void-- — APPROVED** [review]
Awesome! Thanks Zakiya!

**Comment by void--** [comment]
Left a quick question/comment

**Comment by void--** [comment]
ahhh I see -- so, if you enter the following command:

`terminus site:create adfkskjdfsjkadfs "asdfkjas" "Drupal 8" --org=""`

It says `[error]  Could not find an user-organization membership identified by .`

But I think in the script $org will still be an empty string, so maybe we should do:

`$orgoption = ($org === "") ? "" : "--org=\"$org\"";`

What do you think?

**Comment by zakiya** [comment]
I updated to the latest version of Terminus (2.0.1)  and now I can't recreate the problem. Sorry to have bothered you.

**Comment by void--** [comment]
no bother! Should I make any changes? I merged the PR :)

**Comment by void--** [comment]
Okay I made a little tweak (I was still getting this error `[error] Could not find an user-organization membership identified by .` with terminus 2.0.1), let me know if it works for you...

And now I get to apologize for blowing up your email ;P

**Pull request merged**
